//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Jekyll.Properties {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Jekyll.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на A propos du programme.
        /// </summary>
        public static string ButtonAbout {
            get {
                return ResourceManager.GetString("ButtonAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Activer l&apos;autoclick efficace.
        /// </summary>
        public static string ButtonAutoclickerToolTip {
            get {
                return ResourceManager.GetString("ButtonAutoclickerToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Retour à la page précédente.
        /// </summary>
        public static string ButtonBackToolTip {
            get {
                return ResourceManager.GetString("ButtonBackToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Fermer le programme.
        /// </summary>
        public static string ButtonCloseToolTip {
            get {
                return ResourceManager.GetString("ButtonCloseToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convertisseur.
        /// </summary>
        public static string ButtonConverter {
            get {
                return ResourceManager.GetString("ButtonConverter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Convertir les valeurs.
        /// </summary>
        public static string ButtonConverterToolTip {
            get {
                return ResourceManager.GetString("ButtonConverterToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Accueil.
        /// </summary>
        public static string ButtonGlobal {
            get {
                return ResourceManager.GetString("ButtonGlobal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Définir une adresse IP.
        /// </summary>
        public static string ButtonIdentifierIPToolTip {
            get {
                return ResourceManager.GetString("ButtonIdentifierIPToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Minimiser le programme.
        /// </summary>
        public static string ButtonMinimToolTip {
            get {
                return ResourceManager.GetString("ButtonMinimToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Nouvelles.
        /// </summary>
        public static string ButtonNews {
            get {
                return ResourceManager.GetString("ButtonNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Voir les nouvelles.
        /// </summary>
        public static string ButtonNewsToolTip {
            get {
                return ResourceManager.GetString("ButtonNewsToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Roulette.
        /// </summary>
        public static string ButtonRoulette {
            get {
                return ResourceManager.GetString("ButtonRoulette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Jouer à la roulette.
        /// </summary>
        public static string ButtonRouletteToolTip {
            get {
                return ResourceManager.GetString("ButtonRouletteToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Trouvez des informations sur l&apos;utilisateur VK.
        /// </summary>
        public static string ButtonVKUserInfoToolTip {
            get {
                return ResourceManager.GetString("ButtonVKUserInfoToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Pour utiliser l&apos;application, utilisez les boutons ci-dessous..
        /// </summary>
        public static string LabelContent1 {
            get {
                return ResourceManager.GetString("LabelContent1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Voir les informations du programme.
        /// </summary>
        public static string ToolTipAbout {
            get {
                return ResourceManager.GetString("ToolTipAbout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Bienvenue!.
        /// </summary>
        public static string Welcome {
            get {
                return ResourceManager.GetString("Welcome", resourceCulture);
            }
        }
    }
}
